CREATE TABLE EMPLOYEES (
    EMP_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100) UNIQUE,
    HIRE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SALARY NUMERIC(10,2),
    DEPARTMENT_ID INTEGER NOT NULL
);

CREATE INDEX IDX_EMP_LAST_NAME ON EMPLOYEES(LAST_NAME);

CREATE OR REPLACE FUNCTION GIVE_RAISE(p_emp_id BIGINT, p_percent NUMERIC)
RETURNS VOID AS $$
BEGIN
    UPDATE EMPLOYEES
    SET SALARY = SALARY + (SALARY * p_percent / 100)
    WHERE EMP_ID = p_emp_id;
END;
$$ LANGUAGE plpgsql;

GRANT SELECT, INSERT, UPDATE, DELETE ON EMPLOYEES TO HR_USER;